table categoria {
  id serial [pk]
  nome varchar(64) [not null, unique]
  valor decimal(10,2) [not null]
}

table matricula {
  id serial [pk]
  matricula char(11) [unique]
  is_ativo boolean [not null, default: true]
  atualizado_em timestamp [not null]
  id_cliente int [ref: - cliente.id]
}

table categoria_cliente {
  id int [pk, increment]
  id_cliente int [ref: - cliente.id]
  id_categoria int [ref: - categoria.id]
  atribuido_em timestamp [not null]
  indexes {
    (id_cliente, id_categoria) [unique]
  }
}

table cliente {
  id serial [pk]
  cpf char(11) [not null, unique]
  nome varchar(128) [not null]
  email varchar(320) [not null]
  telefone varchar(20) [not null]
  nascimento date [not null]
  saldo decimal (10, 2) [not null, default: 0.0]
  senha varchar(145) [not null]
}